services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app:cached
      - /app/node_modules # node_modulesをコンテナ内にマウント
      - /app/.next # .nextをコンテナ内にマウント
      - ~/.ssh:/root/.ssh:ro # ホストの~/.sshディレクトリをコンテナの/root/.sshに読み取り専用でマウント
      - ~/.gitconfig:/root/.gitconfig:ro # ホストの~/.gitconfigをコンテナに読み取り専用でマウント
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
