services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
      - /app/node_modules
      - ~/.ssh:/root/.ssh:ro  # ホストの~/.sshディレクトリをコンテナの/root/.sshに読み取り専用でマウント
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true